---
title: "Minimal EDI package generated using EMLassemblyline and ediutilities"
author: "Joe Futrelle"
date: "2022-01-24"
output: html_notebook
---

Libraries used

```{r}
library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
```

Read example data table

```{r}
data_table <- read.csv(here('nes-lter-minimal.csv'))
data_table$date = ymd_hms(data_table$date)
```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here('nes-lter-minimal-info'), 'nes-lter-minimal', rights='CC0')
```

Compute spatiotemporal coverage

```{r}
# FIXME should this datetime -> date conversion happen in ediutilities?
coverage_dates = as.Date(data_table$date) # coverage is by date with no time info

coverage <- data_coverage(coverage_dates, data_table$latitude, data_table$longitude)
```

Generate the package and insert the parent project node into the resulting EML

```{r}
# use a dummy package ID
pkg_id <- 'knb-lter-nes.999.1'

make_eml(here(),
         dataset.title='Demonstration of minimal EDI package',
         data.table='nes-lter-minimal.csv',
         data.table.description='Example NES-LTER data',
         data.table.name = 'Subset of NES-LTER nutrient data',
         temporal.coverage = c(coverage$startdate, coverage$enddate),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = c(coverage$North, coverage$East, coverage$South, coverage$West),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id)
```
